version: '3'
services:
  bd:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - drowo
    volumes:
      - db:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    networks:
      - drowo
    volumes: 
      - ./server:/app

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    networks:
      - drowo
    volumes: 
      - ./client:/app
  
networks:
  drowo:
volumes:
  db:
